### ISSUE TITLE
Failure building mysqlpython pre-req of lsst_apps on OSX Yosemite

### ISSUE THREAD

**Issue by joezuntz** [lsst/lsst_apps#2]
Hi,

Not sure if this should go here - apologies if not.  
When I try to install lsst_apps on OSX Yosemite I get a failure at the stage of building the mysqlpython.  I'm using the homebrew-provided python (and compilers).

I've put the build log here as it won't let me attach for some reason:
http://pastebin.com/htTmqUkR

Thanks!
Joe Zuntz

**Comment by jdswinbank** [comment]
This is https://github.com/RobertLuptonTheGood/eups/issues/49. It's fixed upstream, but there hasn't been an EUPS release with the fix included. Temporary workarounds include tweaking the EUPS source (as described on that ticket) or, presumably, removing the Homebrew-supplied `distconfig.cfg`.

Internally, this is DM-3754.

**Comment by PaulPrice** [comment]
You don't have to remove `distconfig.cfg`: according to [this](http://stackoverflow.com/questions/4495120/combine-user-with-prefix-error-with-setup-py-install) you can put in `~/.pydistutils.cfg`:

```
[install]
prefix=
```

Be sure to delete this file when done.

**Comment by joezuntz** [comment]
The latter seems to have worked - many thanks!
